### ISSUE TITLE
Docker envirorment and .env for variables

### ISSUE THREAD

**Issue by galloramiro** [Arzanico/geoMelt_App#3]
Metería todo dentro de un Docker para poder facilitar el desarrollo, y guardaría dentro de un .env las variables sensibles, como keys y datos de la base de datos y demás.   
De este modo, cuando alguien quiere desarrollar descarga el repo, corre docker-compose up --build y listo, no hay problemas de requerimientos ni nada.  
Por último guardaria en un  env.template en la carpeta para que cada uno que quiera desarrollar lo complete con sus datos de prueba y se separe así lo que está en producción.   
La persona simplemente le borraria el .template al completar sus datos y listo para andar.   
  
**.env.template**  
```
DJANGO_SECRET_KEY=t2wghmkj6(07*)%4$5ls*j*#mp%b1gjy+*qp)l8e0p9v19g6-6

POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_PASSWORD=example
```
En cuanto al docker copio un ejemplo que suelo usar, para este caso habría que modificarlo un poquito nomás.   
  
**DockerFile**  
```
FROM python:3.6-alpine

ENV PYTHONUNBUFFERED 1 
ENV PYTHONDONTWRITEBYTECODE=1

RUN apk update \
  # psycopg2 dependencies
  && apk add --virtual build-deps gcc python3-dev musl-dev \
  && apk add postgresql-dev \
  # Pillow dependencies
  && apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev \
  # CFFI dependencies
  && apk add libffi-dev py-cffi \
  # Translations dependencies
  && apk add gettext \
  # https://docs.djangoproject.com/en/dev/ref/django-admin/#dbshell
  && apk add postgresql-client

RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY . /app/
```
  
**docker-compose.yml**  
```
version: '3'

services:
  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
  backend:
    container_name: backend
    build: ./backend/app/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
```
